(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")


(depends-on "anzu")
(depends-on "magit")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "yatex")
(depends-on "magic-latex-buffer")
(depends-on "py-autopep8")
(depends-on "ein")
(depends-on "tabbar")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "undohist")
(depends-on "undo-tree")
(depends-on "smartparens")
(depends-on "smooth-scroll")
(depends-on "stan-mode")
(depends-on "windata")
(depends-on "switch-window")

(depends-on "gruvbox-theme")
(depends-on "darktooth-theme")
(depends-on "monokai-theme")

(depends-on "init-loader")
(depends-on "auto-complete")
(depends-on "powerline")
(depends-on "smooth-scrolling")

(depends-on "jedi")
(depends-on "flymake-python-pyflakes")
(depends-on "flymake-cursor")

(depends-on "highlight-indent-guides")

(depends-on "auctex")

(depends-on "highlight-parentheses")
(depends-on "open-junk-file")

(depends-on "markdown-preview-mode")
(depends-on "markdown-toc")

(depends-on "flymd")